language: python

python: "3.7"

before_install:
  - nvm install v14.2.0
  - npm install
  - npm install -g eslint
  - pip install -r requirements.txt
  - pip install pre-commit

script:
  - pre-commit run --all-files

cache:
  directories:
  - $HOME/.cache/pre-commit
